[package]
name = "rust_hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_hello_world"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.2"
